# Generated by Django 4.2.7 on 2025-12-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='current_plan',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('pro', 'Pro Plan'), ('none', 'None')], db_index=True, default='none', help_text='Current subscription plan', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe customer ID', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe subscription ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='inactive', help_text='Current subscription status', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_amount_paid',
            field=models.IntegerField(db_index=True, default=0, help_text='Total amount paid in cents (integer, not floating point)'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['stripe_customer_id'], name='users_user_stripe__26a84b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['subscription_status', 'current_plan'], name='users_user_subscri_bfe7ae_idx'),
        ),
    ]
