# Generated by Django 4.2.7 on 2025-12-27 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_current_plan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stripe customer ID (starts with 'cus_')", max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stripe subscription ID (starts with 'sub_')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_amount_paid',
            field=models.IntegerField(db_index=True, default=0, help_text='Total amount paid in cents (integer, not floating point)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('total_amount_paid__gte', 0)), name='users_user_total_amount_paid_non_negative'),
        ),
    ]
